### ISSUE TITLE
Error for make or install yacc on GO

### ISSUE THREAD

**Issue by QuestionPython** [golang-samples/yacc#5]
hello,
i have `goyacc` comment.
but want install `go tool yacc` on go 1.8
how can do this?

after make also say error : 

~/go/src/github.com/cznic/goyacc$ make
---------
>go fmt
go test
PASS
ok  	github.com/cznic/goyacc	0.002s
go install
go tool vet -printfuncs "Log:0,Logf:1" *.go
golint .
make todo
make[1]: Entering directory '/home/guest/go/src/github.com/cznic/goyacc'
main.go:554:	_ = yyerrok
main.go:706:	_ = yypt // guard against "declared and not used"
main.go:791:	_ = oNoLines //TODO Ignored for now
all_test.go:37:func TODO(...interface{}) string {
all_test.go:39:	return fmt.Sprintf("TODO: %s:%d:\n", path.Base(fn), fl)
main.go:791:	_ = oNoLines //TODO Ignored for now
make[1]: Leaving directory '/home/guest/go/src/github.com/cznic/goyacc'

$ go tool yacc
----------
>~/$ go tool: no such tool "yacc"

help me.

**Comment by questionpython** [comment]
Fix with `goyacc -o output.go input.y` :+1:
